---
title: "Lab 10b"
author: "Catalina Medina and Vladimir Minin"
output: html_document
date: '2022-07-22'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.align = "center"
)
```

## Adding COVID cases and deaths data

So far we have looked at COVID hospitalization data. Let's now add cases and deaths to our exploratory analysis of the COVID pandemic in California.

**1** Familiarize yourself with the new dataset.

**1a.** First, download the California cases and deaths data from the [California Open Data Portal] (https://data.ca.gov/dataset/covid-19-time-series-metrics-by-county-and-state). 

**1b.** Save the csv file into your lab10 local directory and add it to your github repository. 


**1c.** Read the data dictionary that accompanies the data.


**2** Explore time trends


**2a.** For selected counties (same ones we used in the morning), plot time series of cases per 100,000 people in the county.

**2b.** For selected counties (same ones we used in the morning), plot time series of number of tests per 100,000 people in the county.

**2c.** For selected counties (same ones we used in the morning), plot time series of number of deaths per 100,000 people in the county.

**2d.** For selected counties (same ones we used in the morning), plot time series of test positivity -- proportion of positive tests on a given day.

**3** Explore relationships between COVID data streams/indicators

**3a.** Case-to-fatality-ratio (CFR) is an important epidemiological quantity. It is defined as the total number of deaths divided by the total number of  cases over a specified period of time. CFR serves as an upper bound for another important epidemiological unknown -- infection-to-fatality ratio (IFR). Create a plot that shows how CFR was changing during the courseof the pandemic.

**3b.** Plot changes in the case-to-hostpitalization-ratio. Notice that we cannot compute cumulative hospitalization,  so we have to compute these ratios on a daily basis. Notice this task requires joining of hospitalization and cases/deaths data. What are potential problems with summarizing the data this way?

**3c.** Same as 3b, but now plot change of the hospitalization-to-death-ratio.

**3d** Compare cumulative summaries of cases and deaths across all counties over the whole time period.

