---
title: "Lab 10a"
output: html_document
date: '2022-07-22'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.align = "center"
)
```

## Joining data

Our plot from lab 9 improved on the original plot, but one issue it had was the range of the y-axis. Some counties had much higher counts than others, making it hard to see the trends for those with low counts. Missing from the plot was information about how extreme the counts are given the populations of the counties. For this lab we will be improving upon our plot by normalizing county hospitalization counts using their population.

**1.** The first step is joining the hospitalization data from lab 9 with a data set containing populations of California counties. 

**1a.** To join the data you need to decide which is appropriate for this: `inner_join()`, `right_join()`, `left_join()`, or `full_join()`?


**1b.** Read in and examine the data sets to decide which column(s) to join by. Adjust column names as needed.


**1c.** Join the data using the appropriate function. Check if there are the expected number of rows after the join.


**1d.** Now we can create a new column where we scale counts of hospitalized COVID confirmed patients by 100,000 people in the county.


**1e.** Now we will update out lab 9 plots by replacing the y-axis with our new scaled variable. You can update your old plot or the one from the lab 9 solution. Make sure your axis label represents the new variable.


**1f.** Also plot you lab 9 plot and compare. What differences do you see?



## Dates  
We will be working with the COVID hospital data again for this section. Note `read_csv()` attempts to recognize column types such as dates while `read.csv` does not. Sometimes `read_csv()` cannot identify the date format so it will need to be manually set. 

**2a.** Read in the hospital data using `read.csv` and note the column type for `todays_date`. 

We will manually set this column as a date using `as_date()`. If `read_csv()` could not determine the date format we can provide it. We can use `stamp()` to get a list of suggested date formats or we can view a [chart of date formats](https://www.r-bloggers.com/2013/08/date-formats-in-r/). We then select the correct one and provide it as the `format` argument in `as_date()`.

**2b.** Typically `as_date()` can recognize the date format so it does not need to be specified. Make `todays_date` into a date column, don't forget to load in the `lubridate` package.

**3.** Above was an exercise in creating date variables, now we will move on to specifying axis labels with dates. The dates displayed on the axis of our plot are arbitrary and do not necessarily look nice. We will use `scale_x_date()` to manually specify the x-axis of our plot. 

**3a.** First, make a sequence of dates called `date_breaks` that begins at June 1, 2020, ends at June 1, 2022, and is spaced by 6 months. 

As an example examine what `seq(from = as_date("2020-01-01"), to = as_date("2021-01-01"), by = "60 day")` produces. 


**3b.** Now add `scale_x_date(breaks = date_breaks, date_labels = "%b %Y")` to the end of your scaled plot code. Note %b will use the abbreviated month name and %Y will give 4 digit year.

